Laundry response
pennlabs/chatbot pull request #1
Opened 2017-03-31 23:41 UTC by ERHSQuizbowl

Added functionality with laundry keyword. Would like to test.

2017-03-31 23:46 UTC, ajmichaels commented
The JS changes look good.  Could you add your xml files to the .gitignore?

2017-03-31 23:47 UTC, armic requested changes
the JS changes look good; could you add your xml files to the .gitignore?

2017-03-31 23:49 UTC, ajmichaels commented on index.js
> +            let ret = name.concat(": There are ").concat(dryers_available).concat(" available dryers and ")
const ret = `${name}: There are ${dryers_available} available dryers and ${washers_available} washers available!`;

2017-04-01 16:46 UTC, ERHSQuizbowl commented
I fixed it. Ready to merge?

2017-04-01 17:01 UTC, merged